# Generated by Django 4.2.10 on 2025-06-04 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verification_token",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, verbose_name="Email Verification Token"
            ),
        ),
        migrations.AlterField(
            model_name="referral",
            name="referred",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referred_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
