# Generated by Django 4.2.10 on 2025-06-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_email_verification_token_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email_verification_token",
        ),
        migrations.AddField(
            model_name="user",
            name="email_otp",
            field=models.CharField(
                blank=True, max_length=6, null=True, verbose_name="Email OTP"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_attempts",
            field=models.IntegerField(default=0, verbose_name="OTP Attempts"),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_created_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="OTP Created At"
            ),
        ),
    ]
