# Generated by Django 5.2.1 on 2026-03-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_email_verification_token_user_email_otp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_reset_otp",
            field=models.CharField(
                blank=True, max_length=6, null=True, verbose_name="Password Reset OTP"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="password_reset_otp_created_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Password Reset OTP Created At"
            ),
        ),
    ]
