# Generated by Django 5.2.1 on 2026-03-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_password_reset_otp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="admin_notes",
            field=models.TextField(blank=True, verbose_name="Admin Notes"),
        ),
        migrations.AddField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted At"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="industry",
            field=models.CharField(blank=True, max_length=100, verbose_name="Industry"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Is Deleted"),
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(blank=True, max_length=255, verbose_name="Location"),
        ),
        migrations.AddField(
            model_name="user",
            name="notification_preferences",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Notification Preferences"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="years_of_experience",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Years of Experience"
            ),
        ),
    ]
