# Generated by Django 5.2.1 on 2025-05-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ATSScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_title",
                    models.CharField(max_length=255, verbose_name="Job Title"),
                ),
                ("job_description", models.TextField(verbose_name="Job Description")),
                (
                    "score",
                    models.PositiveIntegerField(
                        help_text="Score out of 100", verbose_name="ATS Score"
                    ),
                ),
                (
                    "analysis",
                    models.JSONField(default=dict, verbose_name="Analysis Results"),
                ),
                (
                    "suggestions",
                    models.JSONField(
                        default=list, verbose_name="Improvement Suggestions"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "ATS Score",
                "verbose_name_plural": "ATS Scores",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobTitleSynonym",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Job Title"
                    ),
                ),
                ("synonyms", models.JSONField(default=list, verbose_name="Synonyms")),
            ],
            options={
                "verbose_name": "Job Title Synonym",
                "verbose_name_plural": "Job Title Synonyms",
            },
        ),
        migrations.CreateModel(
            name="KeywordMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=100, verbose_name="Keyword")),
                (
                    "found",
                    models.BooleanField(default=False, verbose_name="Found in Resume"),
                ),
                (
                    "importance",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        max_length=20,
                        verbose_name="Importance",
                    ),
                ),
                (
                    "context",
                    models.TextField(blank=True, verbose_name="Context in Resume"),
                ),
            ],
            options={
                "verbose_name": "Keyword Match",
                "verbose_name_plural": "Keyword Matches",
            },
        ),
        migrations.CreateModel(
            name="OptimizationSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(max_length=100, verbose_name="Resume Section"),
                ),
                (
                    "original_text",
                    models.TextField(blank=True, verbose_name="Original Text"),
                ),
                (
                    "suggested_text",
                    models.TextField(blank=True, verbose_name="Suggested Text"),
                ),
                ("reason", models.TextField(verbose_name="Reason for Suggestion")),
                (
                    "applied",
                    models.BooleanField(
                        default=False, verbose_name="Applied to Resume"
                    ),
                ),
            ],
            options={
                "verbose_name": "Optimization Suggestion",
                "verbose_name_plural": "Optimization Suggestions",
            },
        ),
    ]
