# Generated by Django 5.2.1 on 2025-05-19 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ats_checker", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="atsscore",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ats_scores",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="keywordmatch",
            name="ats_score",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="keyword_matches",
                to="ats_checker.atsscore",
            ),
        ),
        migrations.AddField(
            model_name="optimizationsuggestion",
            name="ats_score",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="optimization_suggestions",
                to="ats_checker.atsscore",
            ),
        ),
    ]
