# Generated by Django 5.2.1 on 2026-03-02 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cover_letters", "0001_initial"),
        ("resumes", "0003_resume_deleted_at_resume_is_deleted"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_title",
                    models.CharField(max_length=255, verbose_name="Job Title"),
                ),
                (
                    "company_name",
                    models.CharField(max_length=255, verbose_name="Company Name"),
                ),
                ("job_url", models.URLField(blank=True, verbose_name="Job URL")),
                (
                    "job_description",
                    models.TextField(blank=True, verbose_name="Job Description"),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Minimum Salary",
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Maximum Salary",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Location"
                    ),
                ),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("remote", "Remote"),
                            ("onsite", "Onsite"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="onsite",
                        max_length=10,
                        verbose_name="Work Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("wishlist", "Wishlist"),
                            ("applied", "Applied"),
                            ("phone_screen", "Phone Screen"),
                            ("interview", "Interview"),
                            ("technical", "Technical"),
                            ("offer", "Offer"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="wishlist",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "applied_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Applied Date"
                    ),
                ),
                (
                    "response_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Response Date"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Contact Name"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Contact Email"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="e.g. LinkedIn, Indeed, Referral",
                        max_length=255,
                        verbose_name="Source",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "cover_letter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_applications",
                        to="cover_letters.coverletter",
                        verbose_name="Cover Letter",
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_applications",
                        to="resumes.resume",
                        verbose_name="Resume",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Application",
                "verbose_name_plural": "Job Applications",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="InterviewRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "round_number",
                    models.PositiveIntegerField(verbose_name="Round Number"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("phone", "Phone"),
                            ("video", "Video"),
                            ("onsite", "Onsite"),
                            ("technical", "Technical"),
                            ("behavioral", "Behavioral"),
                            ("panel", "Panel"),
                        ],
                        max_length=15,
                        verbose_name="Interview Type",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Scheduled At"
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Duration (minutes)"
                    ),
                ),
                (
                    "interviewer",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Interviewer"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("feedback", models.TextField(blank=True, verbose_name="Feedback")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        default="scheduled",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_rounds",
                        to="job_tracker.jobapplication",
                        verbose_name="Application",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interview Round",
                "verbose_name_plural": "Interview Rounds",
                "ordering": ["round_number"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(verbose_name="Note")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_notes",
                        to="job_tracker.jobapplication",
                        verbose_name="Application",
                    ),
                ),
            ],
            options={
                "verbose_name": "Application Note",
                "verbose_name_plural": "Application Notes",
                "ordering": ["-created_at"],
            },
        ),
    ]
