# Generated by Django 5.2.1 on 2026-03-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="average_ats_score",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Average ATS Score"
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="industry_tags",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Industry Tags"
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="Is Featured"),
        ),
        migrations.AddField(
            model_name="template",
            name="usage_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Usage Count"),
        ),
    ]
