# Generated by Django 5.2.1 on 2026-03-02 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="trial_days",
            field=models.PositiveIntegerField(default=0, verbose_name="Trial Days"),
        ),
        migrations.AddField(
            model_name="transaction",
            name="gateway_order_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Gateway Order ID"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="payment_gateway",
            field=models.CharField(
                choices=[("razorpay", "Razorpay"), ("stripe", "Stripe")],
                default="razorpay",
                max_length=20,
                verbose_name="Payment Gateway",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="refund_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Refund Amount",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="refund_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Refund ID"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="refund_status",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Refund Status"
            ),
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Invoice Number"
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, upload_to="invoices/", verbose_name="PDF File"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice",
                        to="subscriptions.transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
            },
        ),
        migrations.CreateModel(
            name="PromotionalOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Promo Code"
                    ),
                ),
                (
                    "discount_percentage",
                    models.PositiveIntegerField(verbose_name="Discount Percentage"),
                ),
                ("valid_from", models.DateTimeField(verbose_name="Valid From")),
                ("valid_until", models.DateTimeField(verbose_name="Valid Until")),
                (
                    "max_uses",
                    models.PositiveIntegerField(default=100, verbose_name="Max Uses"),
                ),
                (
                    "current_uses",
                    models.PositiveIntegerField(default=0, verbose_name="Current Uses"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "applicable_plans",
                    models.ManyToManyField(
                        blank=True,
                        related_name="promotional_offers",
                        to="subscriptions.subscriptionplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promotional Offer",
                "verbose_name_plural": "Promotional Offers",
            },
        ),
    ]
